services:
    alice:
        hostname: alice
        build:
            dockerfile: Dockerfile-alice
        restart: always
        networks:
            - a_mitm # this ensures that this network is first alphabetically and is assigned eth0
        command: '/bin/bash -c "printf \"`dig +short github.com`\\twww.github.com\\n`dig +short github.com`\\tgithub.com\\n\" >> /etc/hosts && trap : TERM INT; sleep infinity & wait"'
    # To use bob, update BACKEND_URL in git-proxy/app.py to http://bob
    bob:
        hostname: bob
        image: nginx
        volumes:
        - ./git-server/files:/usr/share/nginx/html
        ports:
        - "1000:80"
        environment:
        - NGINX_PORT=80
        networks:
            - a_mitm
    # Uncomment to replace with a smart git server
    # bob:
    #     hostname: bob
    #     image: cirocosta/gitserver-http
    #     ports:
    #         - 1000:80
    #     volumes:
    #         - ./git-server/files:/var/lib/git
    #     networks:
    #         - a_mitm
    eve:
        hostname: eve
        privileged: true
        build: git-proxy/
        sysctls:
            - net.ipv4.ip_forward=1
            - net.ipv6.conf.all.forwarding=1
            - net.ipv4.conf.all.send_redirects=0
        networks:
            - a_mitm
            - db
        volumes:
        - "./git-proxy:/app"
        ports:
        - "8000:8080"
        depends_on:
            eve-db:
                condition: service_healthy
    eve-db:
        image: postgres
        environment:
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=db
        networks:
            - db
        shm_size: 128mb
        volumes:
            - ./db-data:/var/lib/postgresql/data
        healthcheck: # Ensure database is ready before starting MITM proxy
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            interval: 5s
            timeout: 5s
            retries: 50

networks:
    a_mitm:
    db:

